name: Publish to NPM

on:
    workflow_run:
        workflows: ['Deploy Storybook']
        types:
            - completed

jobs:
    publish:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            packages: write
            contents: read
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
                  scope: '@hdriel'

            - name: building package
              run: | # Install npm packages and build lib output before publish
                  npm ci --ignore-scripts --force              
                  npm run build

            - name: publish step
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
