name: "publish repo"

on: 
  push: 
    branches: 
      - main
      
jobs: 
  publish-gpr: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with: 
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: install npm dependencies
        run: npm install
      - name: deploy storybook livedemo
        run: npm run deploy
      - name: publish npm package
        run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    
